VirtoCommerce/vc-module-sitemaps

VirtoCommerce.SitemapsModule.Data/Services/SitemapItemService.cs

 Paged search ordering revision

---

src/VirtoCommerce.SitemapsModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3115

VP-3115: Fix logo

---

src/VirtoCommerce.SitemapsModule.Web/Controllers/Api/SitemapsModuleApiController.cs

https://virtocommerce.atlassian.net/browse/VP-5549
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5549: Fix dashes is allowed for store id

---

src/VirtoCommerce.SitemapsModule.Web/Controllers/Api/SitemapsModuleApiController.cs

https://virtocommerce.atlassian.net/browse/VP-5388
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5388: create unique link for archives

---

src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs

File with incorrect extension shown in the sitemap.
Add extension check.

VP-5415 filter sitemap extensions

---

src/VirtoCommerce.SitemapsModule.Web/Scripts/widgets/store-sitemaps-widget.tpl.html

VP-6648: Add icons to widgets inside Store settings blade

---

src/VirtoCommerce.SitemapsModule.Core/ModuleConstants.cs
src/VirtoCommerce.SitemapsModule.Core/VirtoCommerce.SitemapsModule.Core.csproj
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
tests/VirtoCommerce.SitemapsModule.Tests/VirtoCommerce.SitemapsModule.Tests.csproj

[Validation on settings input fields](https://virtocommerce.atlassian.net/browse/VP-6756)
User can enter negative digits in input fields where values should be positive 
Update platform dependency
Use suitable value type for input validation

VP-6756: Fix validation on settings input fields

---

src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/member-items-select.js
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-items-add.js

https://virtocommerce.atlassian.net/browse/PT-669

PT-670: Fix user and code icons

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
src/VirtoCommerce.SitemapsModule.Core/VirtoCommerce.SitemapsModule.Core.csproj
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
src/VirtoCommerce.SitemapsModule.Web/module.manifest
tests/VirtoCommerce.SitemapsModule.Tests/VirtoCommerce.SitemapsModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/static-content-items-select.js

Blogs are added to the static pages list
https://virtocommerce.atlassian.net/browse/PT-6756

PT-6756: Blogs are added to the static pages list

---

src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CatalogSitemapItemRecordProvider.cs

Generate sitemap for variations when user select category

PT-8356: Generate sitemap for variations when user select category

---

src/VirtoCommerce.SitemapsModule.Core/ModuleConstants.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CatalogSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Web/Localizations/en.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Module.cs

#PT-6834
It is necessary to be able to set the fields "update frequency" and "priority" to the default values.

PT-6834: The ability to set a priority for each sitemap for each type

---

src/VirtoCommerce.SitemapsModule.Core/VirtoCommerce.SitemapsModule.Core.csproj
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapUrlBuilder.cs
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
src/VirtoCommerce.SitemapsModule.Web/module.manifest
tests/VirtoCommerce.SitemapsModule.Tests/VirtoCommerce.SitemapsModule.Tests.csproj

Catalog module dependency version update for SEO link type switching fix
https://virtocommerce.atlassian.net/browse/PT-8263

PT-8263: SEO links type setting fix

---

src/VirtoCommerce.SitemapsModule.Web/package-lock.json
src/VirtoCommerce.SitemapsModule.Web/package.json
src/VirtoCommerce.SitemapsModule.Web/webpack.config.js

feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395

PT-9395: add nodejs-lts support

---

.editorconfig
Directory.Build.props
VirtoCommerce.SitemapsModule.sln.DotSettings
module.ignore
src/VirtoCommerce.SitemapsModule.Core/ModuleConstants.cs
src/VirtoCommerce.SitemapsModule.Core/VirtoCommerce.SitemapsModule.Core.csproj
src/VirtoCommerce.SitemapsModule.Data.MySql/VirtoCommerce.SitemapsModule.Data.MySql.csproj
src/VirtoCommerce.SitemapsModule.Data.PostgreSql/VirtoCommerce.SitemapsModule.Data.PostgreSql.csproj
src/VirtoCommerce.SitemapsModule.Data.SqlServer/VirtoCommerce.SitemapsModule.Data.SqlServer.csproj
src/VirtoCommerce.SitemapsModule.Data/ExportImport/SitemapExportImport.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CatalogSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CustomSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/SitemapItemRecordProviderBase.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/VendorSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapXmlGenerator.cs
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/Module.cs
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
src/VirtoCommerce.SitemapsModule.Web/module.manifest
tests/VirtoCommerce.SitemapsModule.Tests/VirtoCommerce.SitemapsModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10449
PT-10449: Use updated Crud and Search services

PT-10449: Use updated Crud and Search services

---

VirtoCommerce.SitemapsModule.sln
src/VirtoCommerce.SitemapsModule.Core/ModuleConstants.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CatalogSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
src/VirtoCommerce.SitemapsModule.Web/module.manifest
src/VirtoCommerce.SitemapsModule.Web/package-lock.json

feat: Add a Store Setting to Include Product Images.
faet: Update VC references to stable v6
feat: Update package-lock.json.
https://virtocommerce.atlassian.net/browse/PT-14471
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.401.0-pr-64-1ab5.zip

PT-14471: Include Product Images

---

src/VirtoCommerce.SitemapsModule.Data/Services/ISitemapXmlGenerator.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/CatalogSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapUrlBuilder.cs
src/VirtoCommerce.SitemapsModule.Data/Services/SitemapXmlGenerator.cs
src/VirtoCommerce.SitemapsModule.Web/Controllers/Api/SitemapsModuleApiController.cs
src/VirtoCommerce.SitemapsModule.Web/Module.cs
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/static-content-items-select.js

fix: Empty sitemap with either static pages or folders.
https://virtocommerce.atlassian.net/browse/PT-14501
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.402.0-pr-65-9575.zip

PT-14501: Empty sitemap with static page

---

Directory.Build.props
src/VirtoCommerce.SitemapsModule.Core/VirtoCommerce.SitemapsModule.Core.csproj
src/VirtoCommerce.SitemapsModule.Data.MySql/VirtoCommerce.SitemapsModule.Data.MySql.csproj
src/VirtoCommerce.SitemapsModule.Data.PostgreSql/VirtoCommerce.SitemapsModule.Data.PostgreSql.csproj
src/VirtoCommerce.SitemapsModule.Data.SqlServer/VirtoCommerce.SitemapsModule.Data.SqlServer.csproj
src/VirtoCommerce.SitemapsModule.Data/Repositories/SitemapDbContext.cs
src/VirtoCommerce.SitemapsModule.Data/VirtoCommerce.SitemapsModule.Data.csproj
src/VirtoCommerce.SitemapsModule.Web/VirtoCommerce.SitemapsModule.Web.csproj
src/VirtoCommerce.SitemapsModule.Web/module.manifest
tests/VirtoCommerce.SitemapsModule.Tests/VirtoCommerce.SitemapsModule.Tests.csproj

feat: Update to net8
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.800.0-pr-67-52b9.zip

PT-14740: Update to net8

---

.github/workflows/module-ci.yml
src/VirtoCommerce.SitemapsModule.Web/Localizations/de.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Localizations/en.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Localizations/ru.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-detail.js
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-detail.tpl.html

feat: Improved Export catalog items setting UX. Display setting if list has at least one category item.
https://virtocommerce.atlassian.net/browse/VCST-397
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.801.0-pr-68-5300.zip

VCST-397: Improved Export catalog items setting

---

src/VirtoCommerce.SitemapsModule.Data.PostgreSql/VirtoCommerce.SitemapsModule.Data.PostgreSql.csproj
src/VirtoCommerce.SitemapsModule.Web/Localizations/de.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Localizations/en.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Localizations/ru.VirtoCommerce.Sitemaps.json
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-download.tpl.html

fix: Improved localization
https://virtocommerce.atlassian.net/browse/VCST-1118
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.804.0-pr-74-0d7a.zip

VCST-1118: Fix localization

---

src/VirtoCommerce.SitemapsModule.Data/Services/SitemapItemRecordProviders/StaticContentSitemapItemRecordProvider.cs

Old page builder page format is an array of blocks, but new one is the object with two properties (settings and content)
This commit process the both formats to get permalink from the file.
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.805.0-pr-71-2b2b.zip

get permalink for new and old pages formats

---

src/VirtoCommerce.SitemapsModule.Data.PostgreSql/VirtoCommerce.SitemapsModule.Data.PostgreSql.csproj
src/VirtoCommerce.SitemapsModule.Web/Scripts/blades/sitemap-detail.tpl.html

fix: Resolved the issue causing the admin portal to hang when entering a long Sitemap location.
https://virtocommerce.atlassian.net/browse/VCST-800
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.805.0-pr-73-23b2.zip

VCST-800: the admin portal hangs

---

src/VirtoCommerce.SitemapsModule.Data.MySql/Migrations/20240627094553_AddedSitemapContentMode.Designer.cs
src/VirtoCommerce.SitemapsModule.Data.MySql/Migrations/20240627094553_AddedSitemapContentMode.cs
src/VirtoCommerce.SitemapsModule.Data.PostgreSql/Migrations/20240627094817_AddedSitemapContentMode.Designer.cs
src/VirtoCommerce.SitemapsModule.Data.PostgreSql/Migrations/20240627094817_AddedSitemapContentMode.cs
src/VirtoCommerce.SitemapsModule.Data.PostgreSql/Migrations/SitemapDbContextModelSnapshot.cs

fix: Resolves MySqlException: Unknown column s.SitemapMode in field list.
https://virtocommerce.atlassian.net/browse/VCST-1445
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.807.0-pr-75-e9be.zip

VCST-1414: MySqlException: Unknown column s.SitemapMode in field list.
